pipeline {
    environment {
        IMAGE_NAME = 'my-docker-image'
        VERSION = "v${env.BUILD_NUMBER}"
        REPO = 'my-docker-repo'
        CREDENTIALS_ID = 'docker-credentials'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Build the Docker image for the build stage
                    sh "docker build --target build --tag ${IMAGE_NAME}:${VERSION}-build -f Dockerfile ."
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Build and test the Docker image
                    sh "docker build --target test --tag ${IMAGE_NAME}:${VERSION}-test -f Dockerfile ."
                    sh "docker run --rm ${IMAGE_NAME}:${VERSION}-test"
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push the Docker image to the repository
                    docker.withRegistry('https://index.docker.io/v1/', CREDENTIALS_ID) {
                        sh "docker push ${REPO}/${IMAGE_NAME}:${VERSION}-build"
                        sh "docker push ${REPO}/${IMAGE_NAME}:${VERSION}-test"
                    }
                }
            }
        }
    }
}
